name: Build Windows x64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Probar comando simple
        run: echo "Estoy compilando en una VM Windows x64"